//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public struct DistancePartitionStruct
	{
		public DistancePartitionStruct(float degrees_, float distance_) 
		{
			this.degrees = degrees_;
			this.distance = distance_;
		}
		public float degrees;
		public float distance;
	}
}

